// Webhook
export const BULK_CREATE_WEBHOOKS_STARTED = 'BULK_CREATE_WEBHOOKS_STARTED';
export const BULK_CREATE_WEBHOOKS_FINISHED = 'BULK_CREATE_WEBHOOKS_FINISHED';
export const UPDATE_WEBHOOKS_STARTED = 'UPDATE_WEBHOOK_STARTED';
export const UPDATE_WEBHOOKS_FINISHED = 'UPDATE_WEBHOOK_FINISHED';

// Shop
export const FETCH_SHOP_DATA_STARTED = 'FETCH_SHOP_DATA_STARTED';
export const FETCH_SHOP_DATA_FINISHED = 'FETCH_SHOP_DATA_FINISHED';

// Theme
export const FETCH_THEMES_STARTED = 'FETCH_THEMES_STARTED';
export const FETCH_THEMES_FINISHED = 'FETCH_THEMES_FINISHED';
export const FETCH_MAIN_THEME_STARTED = 'FETCH_MAIN_THEME_STARTED';
export const FETCH_MAIN_THEME_FINISHED = 'FETCH_MAIN_THEME_FINISHED';

// Assets
export const FETCH_ASSETS_STARTED = 'FETCH_ASSETS_STARTED';
export const FETCH_ASSETS_FINISHED = 'FETCH_ASSETS_FINISHED';
export const FETCH_ASSET_BY_KEY_STARTED = 'FETCH_ASSET_BY_KEY_STARTED';
export const FETCH_ASSET_BY_KEY_FINISHED = 'FETCH_ASSET_BY_KEY_FINISHED';
export const UPDATE_ASSET_STARTED = 'UPDATE_ASSET_STARTED';
export const UPDATE_ASSET_FINISHED = 'UPDATE_ASSET_FINISHED';
export const DELETE_ASSET_STARTED = 'DELETE_ASSET_STARTED';
export const DELETE_ASSET_FINISHED = 'DELETE_ASSET_FINISHED';

// Config
export const FETCH_CONFIG_STARTED = 'FETCH_CONFIG_STARTED';
export const FETCH_CONFIG_FINISHED = 'FETCH_CONFIG_FINISHED';
export const UPDATE_CONFIG_STARTED = 'UPDATE_CONFIG_STARTED';
export const UPDATE_CONFIG_FINISHED = 'UPDATE_CONFIG_FINISHED';

// Products
export const FETCH_PRODUCTS_STARTED = 'FETCH_PRODUCTS_STARTED';
export const FETCH_PRODUCTS_FINISHED = 'FETCH_PRODUCTS_FINISHED';

// Product
export const FETCH_PRODUCT_STARTED = 'FETCH_PRODUCT_STARTED';
export const FETCH_PRODUCT_FINISHED = 'FETCH_PRODUCT_FINISHED';

// Product GET METAFIELDS
export const FETCH_PRODUCT_METAFIELDS_STARTED = 'FETCH_PRODUCT_METAFIELDS_STARTED';
export const FETCH_PRODUCT_METAFIELDS_FINISHED = 'FETCH_PRODUCT_METAFIELDS_FINISHED';

// Product UPDATE METAFIELDS
export const UPDATE_PRODUCT_METAFIELDS_STARTED = 'UPDATE_PRODUCT_METAFIELDS_STARTED';
export const UPDATE_PRODUCT_METAFIELDS_FINISHED = 'UPDATE_PRODUCT_METAFIELDS_FINISHED';

// Product DELETE METAFIELDS
export const DELETE_PRODUCT_METAFIELD_STARTED = 'DELETE_PRODUCT_METAFIELD_STARTED';
export const DELETE_PRODUCT_METAFIELD_FINISHED = 'DELETE_PRODUCT_METAFIELD_FINISHED';

// Image Crop
export const UPDATE_IMAGE_CROP_STARTED = 'UPDATE_IMAGE_CROP_STARTED';
export const UPDATE_IMAGE_CROP_FINISHED = 'UPDATE_IMAGE_CROP_FINISHED';
